### PR TITLE
Feature/dataset output formats

### PR DESCRIPTION
**Pull request by josvandervelde**
Added schema.org and DCAT-AP as output formats for datasets. You can now request:

- /datasets/1, equivalent to /datasets/1?schema=aiod
- /datasets/1?schema=schema.org
- /datasets/1?schema=dcat-ap

I added this as a generic mechanism, we probably want to do this later for other resources as well. 

For review, it might be nice to start with the jsons in the test/resources folder, to see the results directly.

For information about DCAT-AP, you can download the source code ZIP in https://github.com/SEMICeu/DCAT-AP/releases/tag/v2.1.1, and find a PDF in `releases/2.1.1/dcat-ap_2.1.1.pdf`.

### CODE REVIEW

**Review by arejula27 — APPROVED** [review]
could be a good option to change de converter election to the abstract router, if there is no converter implemented we can just returm 501.

**Comment by josvandervelde** [comment]
> could be a good option to change de converter election to the abstract router, if there is no converter implemented we can just returm 501.

I'm not sure if I understand. Do you mean that each Router instance does specify the FROM and TO type, but not the converter, and that the abstract router tries to find a fitting converter based on the FROM and TO?

This would remove some boilerplate, but would also add a bit more "magic" to the code. It's then not immediately clear that a converter must be created, when looking at the code. I'm thinking that this might hurt the code more than it helps, what do you think? And did I understand your suggestion correctly?

**Comment by arejula27** [comment]
Im not sure how it would be done in python, if it is more complex  dpnt do it. However i think that the output format  could be done in the general router instead of each instance. Maybe with a swich, so clients would now if the format is available. If they ask for a format and it is not, they would receive an error, i think that currently they will just receive de aiod format and a correct status, it could be annoying for client development.

**Comment by arejula27** [comment]
I will re read another time then

**Comment by josvandervelde** [comment]
> I will re read another time then

I created a testcase to test & show this behaviour

**Pull request merged**
